services:

  db:
    container_name: db
    image: postgres:17.2-alpine3.21
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer:4.8.1
    ports:
      - 8081:8080
    depends_on:
      - db
